#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodamPOS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dodampos")]
	public partial class LINQforREPORTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LINQforREPORTDataContext() : 
				base(global::DodamPOS.Properties.Settings.Default.dodamposConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LINQforREPORTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQforREPORTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQforREPORTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQforREPORTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblProvince> tblProvinces
		{
			get
			{
				return this.GetTable<tblProvince>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProvince")]
	public partial class tblProvince
	{
		
		private string _provinceName;
		
		private string _provinceCode;
		
		public tblProvince()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provinceName", DbType="VarChar(50)")]
		public string provinceName
		{
			get
			{
				return this._provinceName;
			}
			set
			{
				if ((this._provinceName != value))
				{
					this._provinceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provinceCode", DbType="VarChar(2)")]
		public string provinceCode
		{
			get
			{
				return this._provinceCode;
			}
			set
			{
				if ((this._provinceCode != value))
				{
					this._provinceCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
